// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"sample/api"
	"sample/api/handler"
)

// Injectors from wire.go:

func InjectServer() (*api.ServerImpl, error) {
	counterHandler := handler.NewCounterHandlerImpl()
	serverImpl := api.NewServerImpl(counterHandler)
	return serverImpl, nil
}
