// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"sample/api"
	"sample/api/handler"
	"sample/internal/config"
	"sample/pkg/domain/repository"
	"sample/pkg/domain/service"
)

// Injectors from wire.go:

func InjectServer() (*api.ServerImpl, error) {
	configConfig := config.ProvideConfig()
	client, err := config.ProvideSqliteDB(configConfig)
	if err != nil {
		return nil, err
	}
	counterRepository := repository.NewSQLCounterRepository(client)
	counterService := service.NewCounterService(counterRepository)
	counterHandler := handler.NewCounterHandlerImpl(counterService)
	serverImpl := api.NewServerImpl(counterHandler)
	return serverImpl, nil
}
