// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sample/ent/counter"
	"sample/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	counterFields := schema.Counter{}.Fields()
	_ = counterFields
	// counterDescCount is the schema descriptor for count field.
	counterDescCount := counterFields[0].Descriptor()
	// counter.CountValidator is a validator for the "count" field. It is called by the builders before save.
	counter.CountValidator = counterDescCount.Validators[0].(func(int) error)
}
